### ISSUE TITLE
Translation disappeared from Transifex

### ISSUE THREAD

**Issue by p-bo** [glpi-project/doc-install#27]
Hi, wanted to continue on translation, but
https://www.transifex.com/teclib/glpi-install
is no longer accessible - was moved or so?

Thanks :)

**Comment by trasher** [comment]
As far as I know, it's always been on https://www.transifex.com/glpi/glpi-install :)

**Comment by p-bo** [comment]
Weird, had wrong url in browser history – sorry for that…
