### ISSUE TITLE
wrong file locations

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/doc-install#48]
in this section :
https://glpi-install.readthedocs.io/fr/latest/install/index.html#files-and-directories-locations 

user is adviced to copy files folder and config folder instead of 
copy files folder CONTEND and config folder CONTEND

**Comment by cedric-anne** [comment]
Hi,

I do not understand what you want to say. Can you explain using sentences from documentation ?

Regards

**Comment by ladenree76000** [comment]
https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations :

_"GLPI configuration will be stored in /etc/glpi, just copy the **config directory** to this place. GLPI requires read rights on this directory to work; and write rights during the installation process.

GLPI data will be stored in /var/lib/glpi, just copy the **files directory** to this place. GLPI requires read and write rights on this directory."_

in the french version it is right  : 

_"La configuration de GLPI sera stockée dans /etc/glpi/, copier simplement le **contenu du dossier** config à cet endroit. GLPI requiert un accès en lecture sur ce dossier pour fonctionner, et un accès en écriture lors de l’installation.

Les données de GLPI seront stockées dans /var/lib/glpi/, copier le **contenu du dossier** files à cet endroit. GLPI requiert les droits en lecture et écriture sur ce dossier."_
