### ISSUE TITLE
[Question]What is the "php bin/console" subcommand to list the installed plugins and their versions

### ISSUE THREAD

**Issue by sebma** [glpi-project/doc-install#72]
Hi,
To prepare a GLPI migration to another platform, I need the list of the installed plugins and their versions.

What is the "php bin/console" subcommand to list the installed plugins and their versions ?

**Comment by cedric-anne** [comment]
Hi,

There is no such command yet. You have to get this information in `Setup > General > System` page, where you will find a `Plugins list` section.
