### ISSUE TITLE
PHP version 8.1 - can't create MySQL DB

### ISSUE THREAD

**Issue by luxzg** [glpi-project/doc-install#73]
There was a pull request earlier this year:
https://github.com/glpi-project/doc-install/pull/62

But I've been trying to use GLPI version 10 (10.0.5) and PHP8.1 (8.1.2) and it failed database creation.
I had to go to PHP 8.0 (8.0.25) for this step to go through.

That means that documentation is still wrong, it should say "maximum version = 8.0" not "8.1"

**Comment by cedric-anne** [comment]
Version 8.1 is supported and many people are using it.

If you encounter issues, you should give some more details on a new issue in https://github.com/glpi-project/glpi, so we can try to fix it.
