### ISSUE TITLE
glpi 10 maximum php version

### ISSUE THREAD

**Issue by zim333** [glpi-project/doc-install#82]
Hello team,

cedric-anne said here (https://github.com/glpi-project/glpi/issues/13758) that glpi is supposed to be compatible with php8.2.

But the documentation here https://github.com/glpi-project/doc-install/blob/master/source/prerequisites.rst#php said that php8.1 is maximum version.

Is it needed to update the doc ?

Best regards.

**Comment by cedric-anne** [comment]
Hi,

Fixed by #83
