### ISSUE TITLE
Please merge cs_CZ translation from Transifex

### ISSUE THREAD

**Issue by p-bo** [glpi-project/doc-install#9]
Thanks :)

**Comment by trasher** [comment]
This has been done. But readthedocs sems to fail on translations on this doc :/

**Comment by trasher** [comment]
All languages affected... In facts, this is broken since the beginning; something wrong with readthedoc/the config/whatever ; I do not know :(

**Comment by p-bo** [comment]
I see. Just idea - contributed to other project using readthedoc,
translated using .po - Linux Mint documentation:
http://linuxmint-installation-guide.readthedocs.io/cs/latest/
https://translations.launchpad.net/linuxmint/latest/+pots/linuxmint-installation-guide/cs/+translate

What about contact Mint developers about it? Maybe they had similar
problems and know solution…

2018-04-20 8:26 GMT+02:00 Johan Cwiklinski <notifications@github.com>:
