### ISSUE TITLE
Removing the `install` directory after installation

### ISSUE THREAD

**Issue by AKorezin** [glpi-project/doc-install#92]
## Summary

The post-installation section of the documentation suggests removing the installation directory, but this breaks the `db:check_schema_integrity` console command.

The same problem has been discussed in
1. https://github.com/glpi-project/glpi/issues/12924.
1. https://github.com/glpi-project/glpi/issues/15933.

Could you provide correct guidance on how to properly remove the installation directory?

## Details

https://github.com/glpi-project/doc-install/blob/3c7ef2f672c8d06c475e4a93204143d4ee8aa23d/source/install/index.rst?plain=1#L136

> An extra step would be to secure (or remove) installation directory

If I remove the `install` directory after installation, then `bin/console db:check_schema_integrity` shows an error because the `getEmptySchemaPath` function returns `null`.

## Versions

GLPI version: *10.0.11*

**Comment by trasher** [comment]
Install directory should not be removed, but it can still be secured, we'll update documentation on this point.

**Comment by AKorezin** [comment]
I have another question, since everything goes through `public/index.php`, is it still necessary to protect the `install` directory?

**Comment by cedric-anne** [comment]
> I have another question, since everything goes through `public/index.php` and the root is `public`, is it still necessary to protect the `install` directory?

Yes, it is. We may improve this in the future, but in GLPI 10.0 it is still recommended to protect this directory.

**Comment by trasher** [comment]
Using `public` dir as webroot is still just a recommandation, and is not mandatory at all in 10.0.x.

**Comment by AKorezin** [comment]
I'd like to revisit this issue because I finally implemented the new behavior without removing the install directory. It's not mentioned anywhere in the documentation, but it has a representation in the code. https://github.com/glpi-project/glpi/blob/3e852c14988267dfaa9ce191d8c4ad5244aefefc/src/Central.php#L484-L489

```php
if (file_exists(GLPI_ROOT . "/install/install.php")) {
    $messages['warnings'][] = sprintf(
        __('For security reasons, please remove file: %s'),
        "install/install.php"
    );
}
```
So it is still recommended to add the `.htaccess` file and remove the `install.php` file at the same time, but not the whole install directory?

**Comment by cedric-anne** [comment]
> So it is still recommended to add the `.htaccess` file and remove the `install.php` file at the same time, but not the whole install directory?

Yes, you must ensure that the installation script cannot be accessed by a non expected user. Removing it is the best way to do this.
